### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by JamesBrandts** [NateHawk85/Nathans-DnD5e-Foundry-Modules#11]
Very useful, I have a big group and this will help.
When executed the console return a syntax error, changed the first line to:

let activeUsers = await game.users;

and now it works just fine, thanks

**Comment by NateHawk85** [comment]
Hi James. I assume you're talking about [Pull Players to GM Scene](https://github.com/NateHawk85/Nathans-DnD5e-Foundry-Modules/blob/6bd2f254fdb0bb5184ff047818f51dfe89e040f3/Macros/Utility/Pull%20Players%20to%20GM%20Scene.js)? If so, you'll notice that it requires the "findActiveUsers" macro to also be present in order to run. I generally keep those "Function" macros installed, then reference them from other places.
